### ISSUE TITLE
[Query] Can I check a crt file in local when it is expired?

### ISSUE THREAD

**Issue by SusilRamarao** [dyaa/ssl-checker#101]
So I have a bunch of certificates which needs to be checked every once in a week if it is expired or not and give an notification prior to expiry.. so will this node package help to check expiry? Thanks. If not can you recommend any other package.

**Comment by Silvano14** [comment]
Hi Susil, i used this library and i can say that it's a simple library to check a ssl certificate. As you can see from the code, this library use the [TLS](https://nodejs.org/api/tls.html) module

**Comment by dyaa** [comment]
Hi, I built this library to be used internally then I decided to publish it so others can benefit, I'm not asking it to do more, Everyone is also welcomed to contribute.
