### ISSUE TITLE
ISO String

### ISSUE THREAD

**Issue by DesignyourCode** [dyaa/ssl-checker#20]
The ability to set the return format of the dates would be great.

Currently I am having to convert them after the return which is a little untidy:

```
return await sslChecker(domain)
    .then(res => {
        /** Make sure we return a valid date format for the frontend */
        res['valid_from'] = new Date(res.valid_from).toISOString();
        res['valid_to'] = new Date(res.valid_to).toISOString();
        return res;
```

**Comment by dyaa** [comment]
Good One, Will do that this weekend and will add typings (typescript) as well :)

**Comment by DesignyourCode** [comment]
Great, thank you so much. Happy to help test.

**Comment by dyaa** [comment]
Made a new [release](https://github.com/dyaa/ssl-checker/releases/tag/v2.0.0) with your request, Small breaking changes worth to check 😉 

Feel free to re-open the issue for any updates 

Thank you for reporting again

**Comment by DesignyourCode** [comment]
Sorry for the late reply. I did implement this and sort out the breaking change and all works perfectly. Thank you so much
