### ISSUE TITLE
Module has no default export

### ISSUE THREAD

**Issue by amrsobhy** [dyaa/ssl-checker#39]
I'm using the default snippet in typescript 

```
import sslChecker from "ssl-checker";

const getSslDetails = async hostname => await sslChecker("google.com");
console.log(getSslDetails);

```

![Screenshot 2020-03-02 at 23 20 58](https://user-images.githubusercontent.com/6784122/75723446-a2ac9000-5cdc-11ea-9347-82cdd8956b31.png)

**Comment by dyaa** [comment]
And what if you imported the module like this?

> import * as sslChecker from "ssl-checker";

**Comment by amrsobhy** [comment]
yea, tried all the variations 

````
This expression is not callable.
  Type 'typeof import("/Users/amrsobhy/dldl/functions/node_modules/ssl-checker/lib/index")' has no call signatures.ts(2349)

`````
![Screenshot 2020-03-03 at 16 49 30](https://user-images.githubusercontent.com/6784122/75792989-0089b800-5d6f-11ea-8ad1-74adab7a0ac6.png)

**Comment by sherifnada** [comment]
Seeing the same issue on my end as well

**Comment by FaaPz** [comment]
Same for me... any progress? 👀

**Comment by dyaa** [comment]
Sorry for the late response, Should be fixed by now
