### ISSUE TITLE
subjectaltname causing valid cert to fail

### ISSUE THREAD

**Issue by khpeet** [dyaa/ssl-checker#538]
It looks like in the latest release a change was made specifically on this line, requiring `subjectaltname`: https://github.com/dyaa/ssl-checker/blob/master/src/index.ts#L57

According to the TLS docs [here](https://nodejs.org/api/tls.html#tlssocketgetpeercertificatedetailed), that is an optional field in a cert response, so I'm confused on why this module is requiring that for a valid cert, when it isn't required for a cert to be valid. 

Requesting that this check be removed: `!subjectaltname`

**Comment by dyaa** [comment]
Great, how about proposing a change request?

**Comment by khpeet** [comment]
Sure - #539

**Comment by khpeet** [comment]
Thanks for merging @dyaa - greatly appreciate!

**Comment by dyaa** [comment]
Well, thank you for your contribution 🙌
