### ISSUE TITLE
Create new release 2.0.10

### ISSUE THREAD

**Issue by khpeet** [dyaa/ssl-checker#544]
Create new release 2.0.10 - for latest commit with updated feature: https://github.com/dyaa/ssl-checker/pull/539

**Comment by dyaa** [comment]
It was [created](https://www.npmjs.com/package/ssl-checker?activeTab=versions), or do you mean release notes?

**Comment by khpeet** [comment]
ah missed- that, thanks! Yeah I was looking at releases directly in this repo
